version: '3.10'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  streamlit:
    image: python:3.10-slim
    volumes:
      - .:/app
    working_dir: /app
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - fastapi